name: expense_buddy
description: ExpenseBuddy Flutter App

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.5

  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4

  sqflite: ^2.4.0
  path_provider: ^2.1.4

  fl_chart: ^0.69.0
  intl: ^0.19.0

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
